import Head from 'next/head';
import { Navbar } from '@/components/index';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Next Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar title="Next Image Gallery" />
      {children}
    </>
  );
};

export default Layout;
