import Head from 'next/head';
import { Navbar, Sidebar } from '@/components/index';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Next Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar title="Next Image Gallery" />
      <div className="flex">
        <Sidebar />
        {children}
      </div>
    </>
  );
};

export default Layout;
