import Head from 'next/head';
import Image from 'next/image';
import { FaHeart } from 'react-icons/fa';
import { Navbar, Sidebar } from '@/components/index';
import { useFirestore } from '@/hooks/index';

const Home = () => {
  const [docs, loading, error] = useFirestore('images');

  if (loading) {
    return <h1>Loading</h1>;
  }

  return (
    <div className="flex flex-col">
      <Head>
        <title>Next Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar title="Next Image Gallery" />
      <div className="flex relative">
        <Sidebar />
        <div className="flex w-full h-screen justify-center items-center gap-5">
          {docs !== null &&
            docs.map((doc) => (
              <div key={doc.id} className="card shadow max-w-sm">
                <figure className="relative w-full h-[200px]">
                  <Image
                    src={doc.url}
                    alt="Sunset in the mountains"
                    layout="fill"
                    objectFit="cover"
                  />
                </figure>
                <div className="card-body">
                  <h2 className="card-title">
                    <span className="text-primary">Next + Tailwind</span>{' '}
                    <FaHeart className="inline text-secondary" />
                  </h2>
                  <p>
                    Next and Tailwind CSS are a match made in heaven, check out
                    this article on how you can combine these two for your next
                    app.
                  </p>
                  <div className="card-actions">
                    <button className="btn btn-secondary">More info</button>
                  </div>
                </div>
              </div>
            ))}
        </div>
      </div>
    </div>
  );
};

export default Home;
